"""Pin D1's train/val/test split, because D1 ships without one.

The dataset has no official split, so any comparison against a published number
on D1 is a comparison against a different split. This script makes ours explicit
and fixed, and makes it impossible to change it by accident.

Grouping was checked before splitting randomly. module_metadata.json holds
exactly {image_filepath, anomaly_class} for each of the 20,000 crops -- no site,
no flight, no inspection date, no source frame, no module id. There is nothing to
group on, so a stratified random split is the correct choice here. If a grouping
field ever appears, this script is wrong and D2's contamination problem arrives
in a new costume: see docs/DATA.md and ADR 0002.

Ratio is 70/15/15, stratified per class, seed 0, chosen off the *rare* classes
rather than the common ones. Diode-Multi has 175 images and becomes 122/26/27.
**Per-class recall on ~26 val or ~27 test images has a wide interval and must
always be reported with its support count beside it.** One extra misclassified
Diode-Multi image moves its recall by ~4 points.

Two outputs, deliberately:
  data/d1_split.json    the full 20,000-entry assignment. Gitignored, ~400 KB,
                        regenerated by re-running this script.
  configs/d1_split.json committed, ~1 KB: the seed, the ratios, the counts, and
                        a SHA-256 of the canonical assignment. data.py recomputes
                        that hash on every load and refuses to run if it differs,
                        so regenerating the split with a different seed fails
                        loudly instead of silently changing what "val" means.

    python scripts/split_d1.py

Deterministic and idempotent -- re-running leaves the working tree clean.
"""
from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
META = REPO / "data" / "d1" / "module_metadata.json"
FULL = REPO / "data" / "d1_split.json"
PINNED = REPO / "configs" / "d1_split.json"

SEED = 0
PCT = {"train": 70, "val": 15}          # test takes the remainder
N_TOTAL = 20_000
N_CLASSES = 12


def canonical(assignment: dict[str, str]) -> str:
    """The exact bytes the committed hash covers: sorted "path,split" lines."""
    return "\n".join(f"{p},{s}" for p, s in sorted(assignment.items()))


def split_hash(assignment: dict[str, str]) -> str:
    return hashlib.sha256(canonical(assignment).encode("utf-8")).hexdigest()


def main() -> int:
    meta = json.loads(META.read_text(encoding="utf-8"))

    extra = {k for v in meta.values() for k in v} - {"image_filepath", "anomaly_class"}
    assert not extra, f"metadata gained fields {sorted(extra)} -- check for grouping first"

    by_class: dict[str, list[str]] = {}
    for entry in meta.values():
        by_class.setdefault(entry["anomaly_class"], []).append(entry["image_filepath"])

    rng = random.Random(SEED)
    assignment: dict[str, str] = {}
    counts: dict[str, dict[str, int]] = {}
    for cls in sorted(by_class):
        paths = sorted(by_class[cls])       # sort first: dict order must not leak in
        rng.shuffle(paths)
        n = len(paths)
        # Integer arithmetic, not round(n * 0.7). 175 * 0.15 is 26.2499...,
        # and which side of an integer a float lands on is not a split policy.
        n_tr, n_va = n * PCT["train"] // 100, n * PCT["val"] // 100
        parts = {"train": paths[:n_tr], "val": paths[n_tr:n_tr + n_va], "test": paths[n_tr + n_va:]}
        for split, ps in parts.items():
            assignment.update(dict.fromkeys(ps, split))
        counts[cls] = {s: len(ps) for s, ps in parts.items()} | {"total": n}

    # The guarantees. Every one of these has failed on some project.
    splits = {s: {p for p, v in assignment.items() if v == s} for s in ("train", "val", "test")}
    assert not (splits["train"] & splits["val"]), "train and val overlap"
    assert not (splits["train"] & splits["test"]), "train and test overlap"
    assert not (splits["val"] & splits["test"]), "val and test overlap"
    assert sum(len(v) for v in splits.values()) == N_TOTAL, "split does not cover all 20,000"
    assert len(assignment) == N_TOTAL, f"expected {N_TOTAL} entries, got {len(assignment)}"
    assert len(counts) == N_CLASSES, f"expected {N_CLASSES} classes, got {len(counts)}"
    for cls, c in counts.items():
        for s in ("train", "val", "test"):
            assert c[s] > 0, f"class {cls} is absent from {s}"

    order = sorted(counts, key=lambda c: -counts[c]["total"])
    print(f"{'class':<16} {'total':>6} {'train':>6} {'val':>5} {'test':>5}")
    for cls in order:
        c = counts[cls]
        print(f"{cls:<16} {c['total']:>6} {c['train']:>6} {c['val']:>5} {c['test']:>5}")
    tot = {s: sum(c[s] for c in counts.values()) for s in ("total", "train", "val", "test")}
    print(f"{'TOTAL':<16} {tot['total']:>6} {tot['train']:>6} {tot['val']:>5} {tot['test']:>5}")

    digest = split_hash(assignment)
    FULL.parent.mkdir(parents=True, exist_ok=True)
    FULL.write_text(
        json.dumps({"seed": SEED, "sha256": digest, "assignment": assignment}, indent=1, sort_keys=True),
        encoding="utf-8", newline="\n",
    )
    PINNED.write_text(
        json.dumps(
            {
                "_": "GENERATED by scripts/split_d1.py -- do not hand-edit. The full "
                     "assignment lives in data/d1_split.json (gitignored); this file "
                     "pins it. sha256 is over the sorted 'image_filepath,split' lines.",
                "seed": SEED,
                "ratios_pct": {"train": PCT["train"], "val": PCT["val"],
                               "test": 100 - PCT["train"] - PCT["val"]},
                "total": tot["total"],
                "sha256": digest,
                "counts": {cls: counts[cls] for cls in order},
            },
            indent=2,
        ) + "\n",
        encoding="utf-8", newline="\n",
    )
    print(f"\nsha256 {digest}")
    print(f"wrote {FULL.relative_to(REPO).as_posix()} (gitignored) "
          f"and {PINNED.relative_to(REPO).as_posix()} (committed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
